2069 message retry attributes
jamesagnew/hapi-fhir pull request #2076
Opened 2020-09-14 17:37 UTC by tadgh

Closes #2069 

So, Spring Messaging's MessageHeaders class is strictly not deserializable by any of Jackson's default functionality, due to the fact that it is immutable. Jackson requires a default constructor, or some creator, and MessageHeaders just doesn't play nice with that. * 

* What has been done here is replace the usage of MessageHeaders with a homegrown equivalent called `HapiMessageHeaders`, which performs the same function as MessageHeaders, but is mutable. It also contains helper functions to retrieve these particular headers which are currently relevant to the functionality of Retrying. 
* ResourceModifiedMessage and its related Json classes have been repackaged, and moved out of the subscription module. The subscription module still uses the same old class, but it now extends a base class instead. 
* Test has been added for serialization and deserialization of the new classes. 
* `BaseJsonMessage` now contains member variable of type `HapiMessageHeaders`

2020-09-14 19:28 UTC, fil512 requested changes

2020-09-14 19:28 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/json/HapiMessageHeaders.java
> +    public static String RETRY_COUNT_HEADER = "retryCount";
RETRY_COUNT_KEY

2020-09-14 19:28 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/json/HapiMessageHeaders.java
> +    public static String FIRST_FAILURE_HEADER = "firstFailure";
FIRST_FAILURE_TIMESTAMP_KEY

2020-09-14 19:28 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/json/HapiMessageHeaders.java
> +    public static String LAST_FAILURE_HEADER = "lastFailure";
LAST_FAILURE_TIMESTAMP_KEY

2020-09-14 19:32 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/BaseResourceModifiedMessage.java
> +	@JsonProperty("parentTransactionGuid")
For now the only thing that cares about the parentTransactionGuid is EMPI, but I feel it is helpful to know which original transaction caused hooks to fire. Seems to me like something we will want. If you disagree, that's fine, I can subclass it out. Let me know

2020-09-14 19:34 UTC, tadgh commented on hapi-fhir-jpaserver-subscription/src/main/java/ca/uhn/fhir/jpa/subscription/match/matcher/subscriber/SubscriptionMatchingSubscriber.java
>  		if (!(theMessage instanceof ResourceModifiedJsonMessage)) {
Actually this was a dead comment. Earlier we agreed that the class won't change, because of the issue of the Pointcuts having their arguments changed, while there are messages in flight.

2020-09-14 19:35 UTC, tadgh commented on hapi-fhir-jpaserver-empi/src/main/java/ca/uhn/fhir/jpa/empi/broker/EmpiMessageHandler.java
> +				.add(BaseResourceModifiedMessage.class, (BaseResourceModifiedMessage) theMsg)
Investigating...

2020-09-14 19:37 UTC, fil512 commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/BaseResourceModifiedMessage.java
> +	@JsonProperty("parentTransactionGuid")
it isn't relevant to channel import so it shouldn't be on that one

2020-09-14 19:39 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/BaseResourceModifiedMessage.java
> +	@JsonProperty("parentTransactionGuid")
:ok_man:

2020-09-14 19:44 UTC, tadgh commented on hapi-fhir-jpaserver-empi/src/main/java/ca/uhn/fhir/jpa/empi/broker/EmpiMessageHandler.java
> +				.add(BaseResourceModifiedMessage.class, (BaseResourceModifiedMessage) theMsg)
This was indeed a waste of characters

2020-09-14 22:02 UTC, tadgh commented on hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/messaging/BaseResourceModifiedMessage.java
> +	@JsonProperty("parentTransactionGuid")
as per our conversation, I am going to move this attribute to a parent class and document it. See a9fb849d497226c331c9b6dfdc7a2f0af32e49cf

2020-09-15 13:11 UTC, fil512 approved these changes

2020-09-18 18:08 UTC, merged