Feature 2020 09 02 term multi version support
jamesagnew/hapi-fhir pull request #2081
Opened 2020-09-15 13:10 UTC by IanMMarshall

Includes changes so far for multi-versioning of CodeSystem (not yet reviewed) and ConceptMap (reviewed by @IanMMarshall).

2020-09-28 21:35 UTC, dmuylwyk commented
My review is underway. I've reviewed 64/109 files. Will continue in the morning.

Remaining:

- changes to tests in hapi-fhir-jpaserver-base;
- all changes in hapi-fhir-jpaserver-migrate; and
- all changes in hapi-fhir-validation.

At a high-level, here are items @IanMMarshall and I need to consider:

- appending version to resource ID may break existing implementations that identify by resource ID;
- conceptmap remains separate from codesystem and valueset;
- current identified by lastUpdated for conceptmap and valueset;
- current identified by last loaded for codesystem;
- delta operations may not have been tested in light of these changes.

2020-09-29 15:34 UTC, dmuylwyk requested changes
Hi, @IanMMarshall. I feel like this is most of the way there but we have some items we need to consider. Here goes:

1. It strikes me that appending the version to the resource ID may break existing implementations that rely on the resource IDs. At a minimum we need to communicate this change. I'm curious: do we actually need distinct resources or could we simply use a single resource with the versions captured in history, still supported by multiple records in the terminology tables? So a specific record in the terminology tables would point to a specific version in the history of a resource. (Not necessarily proposing this change; simply curious whether or not it was investigated.)

1. ConceptMap remains distinct from CodeSystem and ValueSet; that is, a given ConceptMap does not rely on existing data in the terminology tables but is entirely self-encapsulated. I wasn't expecting this to change; however, I'm raising it here as a concern because I anticipate it will become increasingly difficult to integrate those two halves of the terminology code the longer we put it off.

1. We identify the "current" ValueSet and ConceptMap by lastUpdated. I see potential issues here where an older version could be considered "current" following an update.

1. By contrast, the "current" CodeSystem is identified by the last code system loaded. Is this using the TermCodeSystemVersion table...? This seems better than using lastUpdated but may have the same result where an implementation wants to load historical terminology for reference.

1. I don't see any tests related to the delta operations. Do delta operations work with versioned terminology resources?

1. We use the `import-csv-to-conceptmap` and `export-conceptmap-to-csv` CLI commands to import/export ConceptMaps using CSVs. These already have support for source and target CodeSystem versions but no support for the ConceptMap version. These commands should be updated to account for `ConceptMap.version`, perhaps including the version pipe-delimited in the `--url` option or as a separate option for the command. I expect we'd also want to support ValueSet versions with the `--input` and `--output` options. We also need tests for importing/exporting versioned ConceptMaps using these commands.

1. These changes account for `ConceptMap.version`; however, there is no support for ValueSet and CodeSystem versions within a ConceptMap. If a translation request doesn't declare the ValueSet/CodeSystem version to be translated, do we use "current" by default? Is mapping versioned ValueSets/CodeSystems in your requirements?

2020-09-29 16:10 UTC, IanMMarshall commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/VersionIndependentConcept.java
> +	public VersionIndependentConcept(String theSystem, String theCode, String theDisplay, String theSystemVersion) {
I understood the name of this class as being related to the FHIR version rather than Concept version, but I can see how this might be confusing. Renamed to FhirVersionIndependentConcept.

2020-09-29 16:28 UTC, IanMMarshall commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_2_0/2081-multiple-version-code-systems.yaml
> +title: "Terminology loader for LOINC and operations for CodeSystem, ValueSet and ConcepMap will now support
Broken this out into three change logs, one for general terminology, one for LOINC loader and one for the addition of CodeSystem validate-code operation.

2020-09-29 16:29 UTC, IanMMarshall commented on hapi-fhir-jpaserver-api/src/main/java/ca/uhn/fhir/jpa/api/model/TranslationQuery.java
> +	//-- url
Removed.

2020-09-29 16:48 UTC, IanMMarshall commented on hapi-fhir-jpaserver-api/src/main/java/ca/uhn/fhir/jpa/api/model/TranslationRequest.java
> +	private StringType myConceptMapVersion;
The CodeSystem.version is actually captured, where provided, in the `myCodeableConcept` property. Specifically the TranslationRequest is instantiated by the `translate` method in the ConceptMap resource provider classes and the `codeableConcept` property in the request is created and/or populated from the parameters provided to the `translate` method.  The resource provider `translate` methods all support CodeSystem.version as a parameter and include these when creating/populating the `codeableConcept` property.

2020-09-29 17:14 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/ITermConceptMapDao.java
> +	@Query(value="SELECT cm FROM TermConceptMap cm INNER JOIN ResourceTable r ON r.myId = cm.myResourcePid WHERE cm.myUrl = :url ORDER BY r.myUpdated DESC")
This assumption is correct. We opted for this approach for reasons of performance and simplicity. The `HFJ_RESOURCE` table is already indexed by update date/time and so need to add a new indexed column on the terminology tables. Also, this will avoid the need to update terminology table rows for previous version when uploading a new version.

I agree however that this should be better documented. Renaming this query to be `getTermConceptMapEntitiesByUrlOrderByMostRecentUpdate` to make this clearer. Also will add a note to this effect as part of planned changes to the HAPI FHIR documentation.

2020-09-29 17:59 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/ITermValueSetDao.java
> +	@Deprecated
Good catch. Done.

2020-09-29 18:13 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
Previously, there was only one ResourceTable row for a given CodeSystem with a specified URL. If a new version of the CodeSystem was loaded, it essentially resulted in an update of the existing resource and so there was never a need to update the resource ID of the CodeSystem resource in the TermCodeSystem table. 

Now that we are supporting multiple versions, there can be multiple ResourceTable rows for a given CodeSystem (each version will have a CodeSystem resource). We only want the TermCodeSystem to be linked to the ResourceTable row for the most recently updated CodeSystem version, and as such I needed to make this column updatable so that we could update it whenever a new version was loaded.

2020-09-29 18:34 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r5/ResourceProviderR5CodeSystemTest.java
> +public class ResourceProviderR5CodeSystemTest extends BaseResourceProviderR5Test {
I added these tests because the Code Cov checker was flagging a bunch of changes that were not covered by tests, so I figured better safe than sorry.

2020-09-29 18:55 UTC, dmuylwyk commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/VersionIndependentConcept.java
> +	public VersionIndependentConcept(String theSystem, String theCode, String theDisplay, String theSystemVersion) {
Ah, I think you're right you're absolutely right. My bad.

2020-09-29 18:58 UTC, dmuylwyk commented on hapi-fhir-jpaserver-api/src/main/java/ca/uhn/fhir/jpa/api/model/TranslationRequest.java
> +	private StringType myConceptMapVersion;
Terrific. Thanks!

2020-09-29 19:01 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/ITermConceptMapDao.java
> +	@Query(value="SELECT cm FROM TermConceptMap cm INNER JOIN ResourceTable r ON r.myId = cm.myResourcePid WHERE cm.myUrl = :url ORDER BY r.myUpdated DESC")
What would be the impact of adding a new column for this flag and indexing on it? You would only need to update one other row when uploading a new version (set the previous `current` to `historical`, for example).

2020-09-29 19:06 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
Understood. So for each version of a given code system, we will have a distinct CodeSystem resource and a row on ResourceTable.

Only the current / most recently updated code system will have a row on TermCodeSystem. Is that right?

2020-09-29 19:32 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
I suspect I'm misunderstanding something here but here goes:

A given resource (e.g. CodeSystem) will have a single row on ResourceTable (the latest version) and one or more rows on ResourceHistoryTable (one for each version).

In the terminology tables, we have TermCodeSystem and TermCodeSystemVersion.

A row on TermCodeSystem should identify the one row in ResourceTable (latest), and also identify a row on TermCodeSystemVersion (the current version).

To date, we've only ever supported a single version so we've had a one-to-one for TermCodeSystem and TermCodeSystemVersion.

It seems to me TermCodeSystemVersion should correspond to a row on ResourceHistoryTable, not ResourceTable. So we could have a single versioned resource for a CodeSystem, identify the latest in TermCodeSystem, and access its history via TermCodeSystemVersion.

I thought that was the purpose of the TermCodeSystemVersion table but I'm probably mistaken. It just strikes me as a code smell that we will create distinct resources and ResourceTable records for each version of CodeSystem.version.

Sanity check: am I making sense?

2020-09-29 19:48 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +		String codeSystemIdentifier;
Renamed to codeSystemUrlAndVersion.

2020-09-29 19:49 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +	private void isCodeSystemLoingOrThrowInvalidRequestException(String theSystemIdentifier, String theProperty) {
Yeah, I guess I should have fixed the name of this method when I made the other changes. Corrected.

2020-09-29 19:53 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +		//-- get the latest ConceptMapVersion if theTranslationRequest has url, but ConceptMapVersion
I think it was supposed to say `get the latest ConceptMapVersion if the TranslationRequest has url but no ConceptMapVersion`. Changed this to `get the latest ConceptMapVersion if theTranslationRequest has ConceptMap url but no ConceptMap version` to make it clearer..

2020-09-29 19:54 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +		//-- get the latest ConceptMapVersion if theTranslationRequest has url, but ConceptMapVersion
Same response.

2020-09-29 20:16 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +						// TODO: The invocation of the size() below does not seem to be necessary but for some reason, removing it causes tests in TerminologySvcImplR4Test to fail.
The test methods throw an exception:

`org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: ca.uhn.fhir.jpa.entity.TermConceptMapGroupElement.myConceptMapGroupElementTargets, could not initialize proxy - no Session`

The exception appears to be triggered when the test methods attempt to log TermConceptMapGroupElement elements. I could have simply removed the log statements from the test class, but I was not sure if this was indicative of another reason why the `size()` method is called below, so I made the note to look into this further later.

2020-09-29 20:20 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermCodeSystemStorageSvcImpl.java
> +		ourLog.info(" * Deleting code system version {}", theCodeSystemVersion.getCodeSystemVersionId());
Good point. I was essentially adapting a message logged by a similar method, `deleteCodeSystem` which does the same thing for TermCodeSystem. I have updated the message to explicitly say `Deleting TermCodeSystemVersion ...`.

2020-09-29 20:47 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermLoaderSvcImpl.java
> +			codeSystemVersionId = "1.0.0";
I actually did this for backwards compatibility (it was previously setting the version to 1.0.0 before these changes). If no version is specified, it should basically populate the version the same way as before.

2020-09-29 20:59 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/TermLoaderSvcImpl.java
> +			codeSystemVersionId = "1.0.0";
Gotcha. I'm not sure I like it but I do understand it.

2020-09-29 20:59 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +						// TODO: The invocation of the size() below does not seem to be necessary but for some reason, removing it causes tests in TerminologySvcImplR4Test to fail.
Gotcha. That's weird.

2020-09-29 21:06 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/BaseLoincTop2000LabResultsHandler.java
> +			myValueSetId = theValueSetId + "-" + versionId;
I am a bit unclear on whether a solution should ever be depending on specific IDs for accessing resources. That aside, the new functionality will only append version to the resource ID if one is provided in configuration. If there is a need to support implementations that depend on the old non-versioned resource IDs, it will still be possible to load LOINC terminology without specifying a version, which will result in a copy of the terminology being loaded with the non-versioned Resource IDs.

2020-09-29 21:07 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/LoincAnswerListHandler.java
> +			valueSetId = answerListId + "-" + codeSystemVersionId;
See my comment above.

2020-09-29 21:09 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/LoincUploadPropertiesEnum.java
> +	LOINC_CODESYSTEM_VERSION("loinc.codesystem.version"),
As mentioned in previous comments, my intention here was to preserve the previous functionality where possible and as such I made the version optional. If no version is specified, then a non-versioned instance of LOINC will be loaded and will be accessible via non-versioned operations.

2020-09-29 21:11 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/resources/ca/uhn/fhir/jpa/term/loinc/loincupload.properties
> +## Key may be omitted if only a single version of LOINC is being kept.
As mentioned previously, the LOINC CodeSystem.version was always being set to 1.0.0 and as such I preserved this functionality in cases where an implementation does not otherwise explicitly specify a CodeSystem.version.

2020-09-29 21:48 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4CodeSystemTest.java
> +	public void testUpdateCodeSystemName() throws IOException {
You are correct, I do not believe that there is a requirement to modify CodeSystem.name. I cannot recall the details, but I believe the intent here was to provide basic test coverage for another case being flagged by the Code Cov check e.g. where an existing CodeSystem was being updated (i.e. but no change to URL or version). 

Have updated the method name to reflect what I think was the true intention of this test.

2020-09-29 21:52 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4CodeSystemValidationTest.java
> +public class ResourceProviderR4CodeSystemValidationTest extends BaseResourceProviderR4Test {
Renamed class to ResourceProviderR4CodeSystemValidateCodeTest.

2020-09-29 22:51 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4CodeSystemValidationTest.java
> +public class ResourceProviderR4CodeSystemValidationTest extends BaseResourceProviderR4Test {
I cannot speak to ResourceProviderR4CodeSystemVersionedTest as this was created by Frank. I opted to duplicate and rename the classes for a couple of reasons:

1. In many cases, I found I was simply duplicating most of the methods in the classes, but with a different `Before` setup. As such, it was much more efficient to simply duplicate the class.

2. I wanted to ensure that the original, non-versioned functionality was not affected by the changes. The easiest way to do this was to keep the original tests intact as much as possible.

Personally, I am not sure how important it is for tests to be discoverable. In the case of future modifications, it should only be necessary to modify tests if those modifications break tests, in which case they will become discoverable.

For the ResourceProviderR4CodeSystemVersionedTest class, I have merged this into ResourceProviderR4CodeSystemTest.

2020-09-29 22:53 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4ConceptMapTest.java
> +	public void testTranslateWithReverseConcaptMapUrlAndVersion() {
Done.

2020-09-29 23:47 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/term/TerminologyLoaderSvcLoincIntegratedTest.java
> +public class TerminologyLoaderSvcLoincIntegratedTest extends BaseJpaR4Test {
The difference between the two is that the `TerminologyLoaderSvcLoincTest` class uses mock implementations of the TermCodeStorageSvc and TermDeferredStorageSvc whereas the `TerminologyLoaderSvcLoincIntegratedTest` uses real implementations created by Spring. I admit the name could be confusing. I have renamed it to `TerminologyLoaderSvcLoincJpaTest` to indicate that it is tied into other JPA services.

2020-09-29 23:47 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/resources/loinc/v267_loincupload.properties
> +loinc.codesystem.version=2.67
Per my earlier comments, I opted to make this optional so as to maintain backwards compatibility.

2020-09-29 23:54 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/resources/loinc/v267_loincupload.properties
> +loinc.answerlist.version=Beta.1
Frank and I discussed this previously with James and decided that we should leave it to sites doing the loading to decide what version to assign to the ConceptMap and answer lists. As part of the documentation updates, I intend to make it clear that if the code system is being versioned, then the code system version will need to be incorporated into these version settings (to ensure that existing versions do not get overwritten).

2020-09-29 23:56 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/test/resources/loinc/v268_loincupload.properties
> +loinc.codesystem.version=2.68
Good catch. This should have been in the optional section. Now fixed.

2020-09-29 23:58 UTC, IanMMarshall commented on hapi-fhir-jpaserver-migrate/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +		trmConceptMap.addIndex("20200910.3", "IDX_CONCEPT_MAP_URL").unique(true).withColumns("URL", "VER");
I do not believe so given that the old index is being dropped before the new index is being added. I tested the migration myself and again when I deployed on the LOINC dev box and did not detect any issues.

2020-09-29 23:59 UTC, IanMMarshall commented on hapi-fhir-jpaserver-migrate/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +		trmValueSet.addIndex("20200923.4", "IDX_VALUESET_URL").unique(true).withColumns("URL", "VER");
Same answer as before. I do not believe this is an issue as the old index is being dropped. As per my previous comment, I have tested this (with PostgreSQL) and there were no issues.

2020-09-30 00:18 UTC, IanMMarshall commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/CommonCodeSystemsTerminologyService.java
> +				url = ((org.hl7.fhir.r5.model.CodeSystem) theCodeSystem).getUrl();
OK, I overlooked this when merging Frank's changes. I have added a test to exercise this in the R5 CodeSystem resource provider test.

2020-09-30 00:20 UTC, IanMMarshall commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java
> +	private org.hl7.fhir.r5.model.ValueSet expandValueSetToCanonical(ValidationSupportContext theValidationSupportContext, IBaseResource theValueSetToExpand, @Nullable String theWantSystemIdentifier, @N
Renamed it to `theWantSystemUrlAndVersion`.

2020-09-30 00:24 UTC, IanMMarshall commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java
> +								.addInclude(new org.hl7.fhir.dstu2.model.ValueSet.ConceptSetComponent().setSystem(codeSystemUrl).setVersion(codeSystemVersion)));
I have backed out this change. I think this was a copy and paste error seeing there was never any intention to support code system versioning for DSTU2.

2020-09-30 01:02 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/ITermConceptMapDao.java
> +	@Query(value="SELECT cm FROM TermConceptMap cm INNER JOIN ResourceTable r ON r.myId = cm.myResourcePid WHERE cm.myUrl = :url ORDER BY r.myUpdated DESC")
The impact would arise due to increasing the number of table write operations that would need to be done each time a new version is loaded (note that I am assuming we would have to do something similar for ValueSet). On top of the table writes, there would be additional overhead to query for the previous current version and to update the index on the column when it is changed.

Perhaps I am overestimating the impact, but at the same time I am not seeing much of a benefit to adding a new column that would justify the added complexity and performance overhead.

2020-09-30 15:07 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/ITermConceptMapDao.java
> +	@Query(value="SELECT cm FROM TermConceptMap cm INNER JOIN ResourceTable r ON r.myId = cm.myResourcePid WHERE cm.myUrl = :url ORDER BY r.myUpdated DESC")
Fair enough, @IanMMarshall. I'm torn between the two approaches.

If an implementer only ever loads terminology sequentially in order of versions, this is a non-issue. However, any updates to previous versions will require any subsequent versions to be updated/reloaded. I think this may be a good point for @jamesagnew to weigh in on.

2020-09-30 15:08 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +		//-- get the latest ConceptMapVersion if theTranslationRequest has url, but ConceptMapVersion
Works for me!

2020-09-30 15:13 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/BaseLoincTop2000LabResultsHandler.java
> +			myValueSetId = theValueSetId + "-" + versionId;
So a versioned implementation would have `ValueSet/loinc-all-2.3.4` (for example), and the implementer would need to account for this change if they were previously expecting `ValueSet/loinc-all`. Conversely, a non-versioned implementation would happily continue using `ValueSet/loinc-all`. Do I have that right?

2020-09-30 15:14 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/LoincUploadPropertiesEnum.java
> +	LOINC_CODESYSTEM_VERSION("loinc.codesystem.version"),
Gotcha. At some point I think we may want to make this mandatory but I accept your reasoning here.

2020-09-30 15:17 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4CodeSystemTest.java
> +	public void testUpdateCodeSystemName() throws IOException {
Gotcha. Thanks!

2020-09-30 15:18 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r4/ResourceProviderR4CodeSystemValidationTest.java
> +public class ResourceProviderR4CodeSystemValidationTest extends BaseResourceProviderR4Test {
Understood. Thanks for the explanation!

2020-09-30 15:18 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/term/TerminologyLoaderSvcLoincIntegratedTest.java
> +public class TerminologyLoaderSvcLoincIntegratedTest extends BaseJpaR4Test {
Gotcha. Thanks!

2020-09-30 15:19 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/provider/r5/ResourceProviderR5CodeSystemTest.java
> +public class ResourceProviderR5CodeSystemTest extends BaseResourceProviderR5Test {
Ah, of course. Thank you!

2020-09-30 15:20 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/test/resources/loinc/v267_loincupload.properties
> +loinc.answerlist.version=Beta.1
Makes sense to me. Thanks!

2020-09-30 15:22 UTC, dmuylwyk commented on hapi-fhir-jpaserver-migrate/src/main/java/ca/uhn/fhir/jpa/migrate/tasks/HapiFhirJpaMigrationTasks.java
> +		trmConceptMap.addIndex("20200910.3", "IDX_CONCEPT_MAP_URL").unique(true).withColumns("URL", "VER");
Cool. I'm always a little wary of such changes with migration tasks. Thanks for validating it.

2020-09-30 16:18 UTC, dmuylwyk approved these changes
Reviewed changes.

@IanMMarshall is looking into delta operations, `import-csv-to-conceptmap`, and `export-conceptmap-to-csv`.

There are a few larger unresolved discussions on this PR that I would like @jamesagnew to weigh in on; otherwise I'm good with these changes.

2020-09-30 18:26 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
In response to your questions:

> Understood. So for each version of a given code system, we will have a distinct CodeSystem resource and a row on ResourceTable.
> 
> Only the current / most recently updated code system will have a row on TermCodeSystem. Is that right?
> 
This is correct. 

In regards to:

> A given resource (e.g. CodeSystem) will have a single row on ResourceTable (the latest version) and one or more rows on ResourceHistoryTable (one for each version).

In regards to:

> It seems to me TermCodeSystemVersion should correspond to a row on ResourceHistoryTable, not ResourceTable. So we could have a single versioned resource for a CodeSystem, identify the latest in TermCodeSystem, and access its history via TermCodeSystemVersion.
>
I disagree. My understanding of ResourceHistoryTable is that it is used to show a `state` history for a given resource. It tracks how and when a resource was created, updated and possibly deleted. The versions in ResourceHistoryTable shows the current state of a Resource after a given point of time. This to me is different from the meaning of CodeSystem.version which is used to represent a given release or published implementation of a CodeSystem. If each new version of a CodeSystem replaces (i.e. invalidates or inactivates) all previous versions, then yes, I think the versioning of CodeSystem would be analogous to the versioning of resources in ResourceTable and ResourceHistoryTable. However, my understanding of the motivation for this change is the idea that there can be multiple actively supported versions of a CodeSystem. As such, I think that each version of a CodeSystem (version in this case meaning CodeSystem.version which is defined outside of the CDR) should be represented by a separate resource.

2020-09-30 21:11 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
Ah, this is really interesting. I think you're right about multiple actively supported versions. I think I agree with you. I expect @jamesagnew will agree as well.

Let's make sure I understand:

So we should have multiple CodeSystem resources with the same value for CodeSystem.url - one for each value of CodeSystem.version. Each resource will have its own row on ResourceTable and one or more rows on ResourceHistoryTable.

Then we should have a single row on TermCodeSystem for all of the CodeSystem resources with the same value for CodeSystem.url. We will have one row on TermCodeSystemVersion for each value of CodeSystem.version for that value of CodeSystem.url, and the single row on TermCodeSystem will point to the "current" or "latest" version on TermCodeSystemVersion.

For operations where the version isn't provided, we look up the "current" or "latest" on TermCodeSystemVersion via TermCodeSystem for that value of CodeSystem.url.

For operations where the version is provided, we look it up directly in TermCodeSystemVersion.

Is that right? Is this also how it works for ValueSets now?

2020-10-01 02:05 UTC, IanMMarshall commented on hapi-fhir-validation/src/main/java/org/hl7/fhir/common/hapi/validation/support/InMemoryTerminologyServerValidationSupport.java
> +	private org.hl7.fhir.r5.model.ValueSet expandValueSetDstu2Hl7Org(ValidationSupportContext theValidationSupportContext, ValueSet theInput, @Nullable String theWantSystemIdentifier, @Nullable String t
Changed all of the remaining `theWantSystemIdentifier` references to `theWantSystemUrlAndVersion`

2020-10-01 13:50 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/data/ITermConceptMapDao.java
> +	@Query(value="SELECT cm FROM TermConceptMap cm INNER JOIN ResourceTable r ON r.myId = cm.myResourcePid WHERE cm.myUrl = :url ORDER BY r.myUpdated DESC")
I agree, I am not sure I am happy with this approach myself (i.e. that a site may need to reload current version after updating a previous version). One other point that I forgot to mention however that eventually tipped me towards the current approach, is the fact that the FHIR specification does not provide any mechanism for specifying that a particular version is the current version. In the terminology loader, we could easily add a config parameter to say that the version being loaded is current, but what if a site is loading or updating terminology using the REST APIs?

I figured that making the latest update the current version was likely the simplest and most consistent way we could manage this until we come to some type of agreement on how this might be otherwise managed by the REST APIs.

2020-10-01 13:57 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
Yes, this is how I expect it should be working for CodeSystems, ValueSets and ConceptMaps (I recognize that ConceptMaps are separate, but the mappings themselves would be to a specific CodeSystem version and so I think they would necessarily have to be linked to the CodeSystem version as well).

2020-10-01 13:58 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/BaseLoincTop2000LabResultsHandler.java
> +			myValueSetId = theValueSetId + "-" + versionId;
Yes, this is my understanding as well.

2020-10-01 14:14 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/loinc/BaseLoincTop2000LabResultsHandler.java
> +			myValueSetId = theValueSetId + "-" + versionId;
Thanks!

2020-10-01 14:33 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/entity/TermCodeSystem.java
> +	@JoinColumn(name = "RES_ID", referencedColumnName = "RES_ID", nullable = false, updatable = true, foreignKey = @ForeignKey(name = "FK_TRMCODESYSTEM_RES"))
Okay. Thanks for fielding my questions. I understand we also identify the ValueSet and ConceptMap versions different in the terminology tables (i.e. no equivalent to TermCodeSystemVersion entity). Thanks again!

2020-10-01 16:24 UTC, merged