Fixed expend filter issue
jamesagnew/hapi-fhir pull request #2175
Opened 2020-11-16 03:40 UTC by frankjtao

Fixed D.2 ValueSet expend filter D.2 issue

2020-11-18 20:48 UTC, IanMMarshall requested changes
This appears to be right to me, but I think that similar changes may be required for DSTU3 and R5 as well.

2020-11-19 06:54 UTC, dmuylwyk requested changes
I'm fairly certain the filter operator should remain EQUAL instead of EXISTS.

2020-11-19 06:54 UTC, dmuylwyk commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/StringUtil.java
> +	public static boolean isStartsWithIgnoreCase(final String theInput, final String thePrefix) {
Hi, @frankjtao and @IanMMarshall.

What is the issue we're trying to solve here? What was the original request?

2020-11-19 06:54 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoValueSetDstu3.java
> +				include.addFilter().setProperty("display").setOp(FilterOperator.EXISTS).setValue(theFilter);
@frankjtao and/or @IanMMarshall, can you explain/justify this change from EQUAL to EXISTS?

Reviewing the FilterOperator value set [here](https://www.hl7.org/fhir/valueset-filter-operator.html), I'm not sure this makes sense. EQUAL seems like the most appropriate fit for a partial-to-complete match. EXISTS simply identifies whether or not the property (in this case the display) is present at all.

I'm calling this out only here; however, I have the same concern for all of the related resource DAOs by FHIR version.

2020-11-19 13:55 UTC, dmuylwyk commented
These appear to be the requirements:

> Matching ngrams appropriately inside a word with usage pattern: /ValueSet/VALUE-SET-ID/$expand?filter=
> 
> For a display text of “Body height”:
> searching on "Bo" or "he" should find it
> searching on "ei" or "dy" should not find it

2020-11-19 13:56 UTC, dmuylwyk commented on hapi-fhir-base/src/main/java/ca/uhn/fhir/util/StringUtil.java
> +	public static boolean isStartsWithIgnoreCase(final String theInput, final String thePrefix) {
Posted the requirements here:

https://github.com/jamesagnew/hapi-fhir/pull/2175#issuecomment-730392028

2020-11-19 13:58 UTC, dmuylwyk requested changes

2020-11-19 13:58 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoValueSetR4.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
This change warrants a changelog entry to indicate $expand with filter not evaluates the display with left-matching by string token, case-insensitive.

2020-11-20 13:11 UTC, dmuylwyk requested changes
Thanks for the changelog entry, @frankjtao.

I remain concerned about the filter operator (`exists` vs. `=`). My interpretation of the standard leads me to understand `exists` should indicate whether the display property is populated _at all_ regardless of the value of the display property. `=` is used to indicate we're evaluating the actual value of the display property. Put another way: we're saying "the filter value equals some or all of the display property value"; we are not saying "the filter value exists within the display property value".

If there's an issue with using the `EQUAL` operator _in the code_, that's a matter of revisiting the implementation and tests. I think the standard is pretty clear here.

I'd really like @IanMMarshall to weigh in on this when he has the time to investigate and consider.

2020-11-20 13:11 UTC, dmuylwyk commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_3_0/2175_valueset_expension_filer_left_match.yaml
> +title: "When expanding a ValueSet using a filter, now evaluates the display with left-matching
Readability.

```suggestion
title: "Expanding a ValueSet using a filter now evaluates the display with left-matching 
```

2020-11-23 21:00 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoValueSetDstu3.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
After examining the changes in BaseTermReadSvcImpl more closely, I agree that enabling the "myDisplayNGram" in the `addDisplayFilterInexact()` method of BaseTermReadSvcImpl class is the correct solution here. That being said, I am now wondering if there is still a need for the `applyFilter` method in the FhirResourceDaoValueSet classes. I think this would only really be needed now for the case where HibernateSearch is not implemented. 

Currently the BaseTermReadSvcImpl class disallows expand with filter in cases where HibernateSearch is not enabled. As such, I would say maybe remove this for now from the FhirResourceDaoValueSetDstu3, FhirResourceDaoValueSetR4 and FhirResourceDaoValueSetR5 classes.

2020-11-23 21:01 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoValueSetR4.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
See comments above in FhirResourceDaoValueSetDao3.

2020-11-23 21:01 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r5/FhirResourceDaoValueSetR5.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
See comments above in FhirResourceDaoValueSetDstu3 and FhirResourceDaoValueSetR4.

2020-11-23 21:03 UTC, IanMMarshall commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +			.andField("myDisplayNGram").boostedTo(1.0f)
I would suggest also adding a test for the expand with filter to the FhirResourceDaoR4SearchWithElasticSearchIT class as well to ensure that this change also works with the Elasticsearch mapping provider.

2020-11-23 21:10 UTC, IanMMarshall requested changes
See my comments.

2020-11-23 21:31 UTC, dmuylwyk reviewed
I concur with @IanMMarshall's review. No additional comments from me.

2020-11-23 21:32 UTC, dmuylwyk commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoValueSetDstu3.java
> +				include.addFilter().setProperty("display").setOp(FilterOperator.EXISTS).setValue(theFilter);
Resolved. We stuck with EQUAL.

2020-11-23 21:33 UTC, dmuylwyk commented on hapi-fhir-docs/src/main/resources/ca/uhn/hapi/fhir/changelog/5_3_0/2175_valueset_expension_filer_left_match.yaml
> +title: "When expanding a ValueSet using a filter, now evaluates the display with left-matching
Resolving. This suggestion was applied.

2020-11-23 21:34 UTC, dmuylwyk approved these changes

2020-11-23 22:42 UTC, frankjtao commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/dstu3/FhirResourceDaoValueSetDstu3.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
@IanMMarshall No. The `applyFilter ` method can't be removed in this case, since `NGram Analyzer` will return entry e.g.  for the display value of 'Systolic blood pressure' with the filter 'lood'. The `applyFilter` will filter out the non-left matching entries.

2020-11-23 22:42 UTC, frankjtao commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r4/FhirResourceDaoValueSetR4.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
Same as above

2020-11-23 22:42 UTC, frankjtao commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/dao/r5/FhirResourceDaoValueSetR5.java
> +			if (isBlank(next.getDisplay()) || !StringUtil.isStartsWithIgnoreCase(next.getDisplay(), theFilter)) {
Same as above

2020-11-24 02:33 UTC, frankjtao commented on hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/term/BaseTermReadSvcImpl.java
> +			.andField("myDisplayNGram").boostedTo(1.0f)
Added 3 more test cases to FhirResourceDaoR4SearchWithElasticSearchIT

2020-11-27 14:49 UTC, IanMMarshall approved these changes
Looks good. Approved.

2020-11-27 19:47 UTC, merged