Remove
jamesagnew/hapi-fhir pull request #2177
Opened 2020-11-17 02:20 UTC by tadgh

2020-11-17 17:15 UTC, nvg-smile commented
Looks great to me, only a few minor changes to consider for the future. We may need to review comments, as they still have many mentions of patient/person. Naming is sometimes inconsistent. Any mention of person and source resource should be updated to golden resource. Considering this is still WIP, we may address those in the future.

2020-11-17 20:07 UTC, nvg-smile requested changes
Great work :)! For the most part - naming convention changes. Exciting to see so much being accomplished so quickly!

2020-11-27 22:13 UTC, nvg-smile reviewed
EMPI to MDM references should be addressed

2020-12-01 08:39 UTC, bdenton commented
Can I please suggest that the `ca.uhn.fhir.rest.server` Java package please be renamed? This package already exists in `hapi-fhir-server` and it creates a  "split package" situation that is a problem in many environments.. notable any sort of OSGi class loading implementation.
cheers, Bill Denton

2020-12-02 15:22 UTC, nvg-smile approved these changes

2020-12-07 18:31 UTC, fil512 approved these changes

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/interceptor/MdmStorageInterceptor.java
> +		if (myGoldenResourceHelper.isDeactivated(theUpdatedResource)) {
I was initially thrown by the term "deactivated" but I think it's a good term here.  It does make me wonder if there's a better one.  What do other mdm systems call this...?

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/MdmResourceFilteringSvc.java
> +		//TODO GGG ask KHS: Skip the infinite loop, whoops. Better way to do this? tighter subscription criteria?
hmm.  I don't understand the question

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/svc/candidate/FindCandidateByScoreSvc.java
> +public class FindCandidateByScoreSvc extends BaseCandidateFinder {
Consider renaming to `FindCandidateByExampleSvc`

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/model/CanonicalIdentityAssuranceLevel.java
> + * HAPI FHIR - Master Data Management
delete this class

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/AssuranceLevelUtil.java
>  public final class AssuranceLevelUtil {
Delete all mdm classes concerning assurance level

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/GoldenResourceHelper.java
> +		PrimitiveTypeComparingPredicate predicate = new PrimitiveTypeComparingPredicate();
Is this actually a `PrimitiveTypeEqualsPredicate` ?

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/GoldenResourceHelper.java
> +	private void validateContextSupported() {
This should probably be a static util function so we can use it elsewhere..

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/GoldenResourceHelper.java
> +}
nitpick this class is getting kind of long.  is there a distinct responsibility in here that could be carved out into a separate class?

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/MdmUtil.java
> +public final class MdmUtil {
MdmResourceUtil?

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/PrimitiveTypeComparingPredicate.java
> +public class PrimitiveTypeComparingPredicate implements BiPredicate {
nitpick: rename to `PrimitiveTypeEqualsPredicate`

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/util/PrimitiveTypeComparingPredicateTest.java
> +		myNegativeTest = patient;
why is there a Patient patient?

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/test/java/ca/uhn/fhir/mdm/util/PrimitiveTypeComparingPredicateTest.java
> +		assertTrue(cut.test(myPositiveTest1, myPositiveTest3));
Nitpick: This test is misleading.  It's not testing transitivity.  It's just testing that three identical resources are all equal to each other.  It doesn't do anything beyond testing that `assertTrue(cut.test(myPositiveTest1, myPositiveTest2));`

2020-12-07 18:31 UTC, fil512 commented on hapi-fhir-server-mdm/src/main/java/ca/uhn/fhir/mdm/util/GoldenResourceHelper.java
> +	private void cloneCompositeField(IBaseResource theFrom, IBaseResource theTo, String field) {
This is really nice!  Will be interesting to see how it evolves as we add survivability rules!

2020-12-09 17:34 UTC, merged